# Control Device constants
CONTROL_DEVICE_DEVICE_AVAILABLE_WAIT_TIME = 5
CONTROL_DEVICE_DEFAULT_WAIT_TIME = 1
CONTROL_DEVICE_POWER_OFF_WAIT_TIME = 5

# Monsoon constants
MONSOON_COLUMN_NAMES = ['time (sec)', 'current (mA)', 'voltage (V)']
MONSOON_MIN_VOLTAGE = 0
MONSOON_MAX_VOLTAGE = 13.5
MONSOON_SAMPLING_FREQUENCY = 5000  # in Hz, for HVPM model
MONSOON_COLLECTED_SAMPLES_PER_BATCH = 100
MONSOON_PARQUET_BUFFER_UPDATE_FREQUENCY = 10  # in seconds
MONSOON_PARQUET_BUFFER_SIZE = (MONSOON_SAMPLING_FREQUENCY // MONSOON_COLLECTED_SAMPLES_PER_BATCH) * MONSOON_PARQUET_BUFFER_UPDATE_FREQUENCY
MONSOON_PARQUET_COMPRESSION = 'SNAPPY'

# Device Recharge constants
DEVICE_RECHARGE_CHECK_CHARGING_LEVEL_FREQUENCY = 60 * 1
DEVICE_RECHARGE_USB_CHANGE_STATE_TIMEOUT = 5
DEVICE_RECHARGE_DEFAULT_MIN_BATTERY_LEVEL_RATIO = 0.30
DEVICE_RECHARGE_DEFAULT_MAX_BATTERY_LEVEL_RATIO = 1.00

# BT iOS Commands constants
BT_IOS_COMMANDS_DEFAULT_MOUSE_DELAY = 0.01
BT_IOS_COMMANDS_DEFAULT_KEYBOARD_TYPE_DELAY = 0.01
BT_IOS_COMMANDS_MOUSE_CLICK_DELAY = 0.01
BT_IOS_COMMANDS_DEFAULT_MOUSE_FAST_ACTIONS_DELAY = 0.01
BT_IOS_COMMANDS_DEFAULT_MOUSE_SLOW_ACTIONS_DELAY = 0.5
BT_IOS_COMMANDS_EXECUTION_TIMEOUT = 1
BT_IOS_COMMANDS_EXTENDED_EXECUTION_TIMEOUT = 2  # used in actions that take longer to complete (e.g. requiring UX actions, animations, etc.)

# USB Library constants
USB_LIBRARY_CHECK_FOR_DEVICE_AVAILABILITY_FREQUENCY = 1
USB_LIBRARY_GET_STATE_ERROR_PATIENCE = 3
USB_LIBRARY_GET_STATE_RETRY_TIMEOUT = 1

# ADB constants
SWITCH_ADB_CONNECTION_STATE_TIMEOUT = 3
ADB_MEASUREMENTS_DEFAULT_SAMPLE_DELAY = 3  # delay between samples, in seconds
ADB_OVER_WIFI_DEFAULT_PORT = 5555
ADB_COMMANDS_EXECUTION_TIMEOUT = 1
ADB_COMMANDS_EXTENDED_EXECUTION_TIMEOUT = 2  # used in actions that take longer to complete (e.g. requiring UX actions, animations, etc.)

# Proxy constants
PROXY_DEFAULT_BROWSER_NAME = "Unknown"
PROXY_DEFAULT_SERVER_IP = "127.0.0.1"
PROXY_DEFAULT_SERVER_PORT = 8443
PROXY_DEFAULT_CERTIFICATE_PATH = "certificates/cert.pem"
PROXY_DEFAULT_PRIVATE_KEY_PATH = "certificates/key.pem"

# Lighthouse constants
LIGHTHOUSE_COMMANDS_WAIT_TIME = 3

# Memory measurements constants
MEMORY_MEASUREMENTS_DEFAULT_INTERVAL = 1  # in seconds

# Other constants
CONTROL_DEVICE_WAIT_TIME_AFTER_ASYNC_CALLS = 5
PAGELOAD_PROXY_WAIT_TIME_AFTER_STARTING = 5
REST_AWAIT_SERVER_WAIT_TIME_AFTER_STARTING = 5
