# time constants in seconds
ONE_HUNDREDTH_OF_A_SECOND = 0.01
TENTH_OF_A_SECOND = 0.1
HALF_A_SECOND = 0.5
ONE_SECOND = 1
TWO_SECONDS = 2
THREE_SECONDS = 3
FOUR_SECONDS = 4
FIVE_SECONDS = 5
EIGHT_SECONDS = 8
SIXTY_SECONDS = 60
